import type { OpportunityRecord, RadarPreferenceRecord, RadarSourceRecord } from './types';

export const mockPreferences: RadarPreferenceRecord = {
  userId: 'demo-user',
  displayName: 'Instructor',
  minHourlyRate: '15',
  minFixedBudget: '50',
  remoteOnly: true,
  preferredKeywords: ['api', 'automation', 'telegram', 'typescript'],
  excludedKeywords: ['commission-only', 'cold calling'],
  allowedCategories: ['automation', 'api', 'bot'],
  notes: 'Bias toward small, winnable tasks that can be finished quickly and paid quickly.',
};

export const mockSources: RadarSourceRecord[] = [
  {
    id: 'src_rss_1',
    name: 'Starter RSS Feed',
    kind: 'rss',
    baseUrl: 'https://example.com',
    feedUrl: 'https://example.com/jobs.rss',
    parserKey: 'rss:generic',
    active: true,
    pollIntervalMin: 30,
    lastPolledAt: new Date().toISOString(),
  },
  {
    id: 'src_html_1',
    name: 'Simple HTML Board',
    kind: 'html',
    baseUrl: 'https://example.org',
    parserKey: 'html:generic',
    active: true,
    pollIntervalMin: 60,
    lastPolledAt: new Date().toISOString(),
  },
];

export const mockOpportunities: OpportunityRecord[] = [
  {
    id: 'opp_1',
    sourceId: 'src_rss_1',
    sourceName: 'Starter RSS Feed',
    canonicalUrl: 'https://example.com/jobs/telegram-bot',
    title: 'Need a Telegram bot automation fixed fast',
    company: 'Small Agency',
    remote: true,
    location: 'Remote',
    summary: 'Quick automation cleanup job with TypeScript and webhook work.',
    rawText: 'Need a Telegram bot automation fixed fast. Looking for someone who can clean up webhook handling and shipping notifications.',
    payType: 'hourly',
    payMin: '20',
    payMax: '30',
    currency: 'USD',
    status: 'new',
    tags: ['telegram', 'automation', 'typescript'],
    fetchedAt: new Date().toISOString(),
    score: {
      fitScore: 84,
      payScore: 78,
      qualityScore: 72,
      effortScore: 68,
      confidenceScore: 81,
      recommendation: 'strong_match',
      reasoningSummary: 'Strong fit because it matches Telegram automation and short-scope API work.',
      strengths: ['Telegram bot experience', 'small scope', 'clear technical asks'],
      risks: ['May be under-scoped', 'needs quick turnaround'],
    },
  },
  {
    id: 'opp_2',
    sourceId: 'src_html_1',
    sourceName: 'Simple HTML Board',
    canonicalUrl: 'https://example.org/tasks/api-integration',
    title: 'Simple API integration task for order sync',
    company: 'Retail Operator',
    remote: true,
    location: 'Remote',
    summary: 'Connect existing backend to third-party order feed and normalize payloads.',
    rawText: 'Need help connecting an order feed API to an existing backend and mapping fields into our internal schema.',
    payType: 'fixed',
    payMin: '75',
    payMax: '120',
    currency: 'USD',
    status: 'shortlisted',
    tags: ['api', 'integration', 'backend'],
    fetchedAt: new Date().toISOString(),
    score: {
      fitScore: 76,
      payScore: 74,
      qualityScore: 70,
      effortScore: 62,
      confidenceScore: 73,
      recommendation: 'maybe',
      reasoningSummary: 'Good technical fit, but scope clarity is only moderate.',
      strengths: ['API integration work', 'clear backend task'],
      risks: ['Integration scope may expand'],
    },
  },
];
